language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsgustavo
deploy-api_key:
  secure: YjqXElM+eCySYf6f/I0G7XXPDabdWiZRArfSW00DAZDf5ir2ebWT4bYrIXB0AwTu4O0EHeMsHCYtHAdeX9Q+k1cQA3VkKuPOjbTTVZiHUlMVTmJXiA9jmutVBiZkyty060kTxyB+VYbkuJ/ErzhmjlGBmTjmyKvzztMkh3Sz9WvjFruFhmlf1TgCB4sRheNVPzfsH55jyxZiBQtiL3Fd3mPeiDwcPnJ1oYITGRfLSKo256ckGM9gxijL+X8KkaAZV/7MY3AhXKUSzv4BYnh0OfkdVVuNtf9BSQzeRbkcmPyUSNOTc80rymoGilc0Z95/boC9apjxB5xXOxbr4gbMvCLDvQ0fP2RkwImx+vcjz+rMku1JjRCtR5WM3k1J1Jy5WyXaUHTCIS2kqmFV9AI+1P5sfEhiYqTltwOgNJrG1h0AGOalYygNYwUsT1kzdqPO1GY3MtH4PD0QJL/rakqNXXDm2S85qsONpW6pOZmZZ+Q+MhHWpOTkqxJOkIh71vhJtQlFfjkJGgtAXz7UZU7AnZC0QwA0zdsXm5luSfb+aVd3gKf0KwcOcYvI2rCiEZvyco1c9j6JWxTc+j6PCBNftp7Gw7u9zP1Cw2E+jfjJGdJeZ52T/CTvpYXzBXnKbZjf1yjakfsSnameX5NTW0iOeFEeV82tPkZqG3cMwpkk0Zc=
